name: outbound
description: "Outbound module for WareHaus - Sales Order, Picking, Packaging & Shipping."
version: 0.0.1
resolution: workspace
homepage:
publish_to: "none"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  core_ui:
    path: ../core_ui
  core_services:
    path: ../core_services
  dio: ^5.0.0
  equatable: ^2.0.5
  get_it: ^9.2.1
  mobile_scanner: ^7.2.0
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
